### ISSUE TITLE
README em vez de arquivos.md

### ISSUE THREAD

**Issue by lucasfeliciano** [cainfpucrio/cainfpucrio.github.io#1]
Curti bastante a ideia e minha sugestão é fazer esse guia só usando o README.md para podermos usar os anchors e fazermos um indice para chegarmos mais rapido ao conteudo procurado e tambem porque se colocarmos eles em arquivos, fica mais dificil visualizar ja que o que veremos vai ser o codigo do markdown em vez dele parseado.

**Comment by leokaplan** [comment]
O indice é previsto no README.
Sobre fazer tudo no readme, acho que usarmos links normais para navegar é razoável e tenho medo do arquivo muito grande e pouco navegável (mesmo com ancoras).
Entendo sua preocupação sobre a visualização. 
Eu pensei no guia sendo usado pelo github, mas podemos discutir alternativas.
Talvez gerar uma versao pdf com links de tempo em tempo ou a cada commit.

**Comment by lucasfeliciano** [comment]
O read-me pode ser um indice que leva aos links do Jekyll :)

**Comment by leokaplan** [comment]
sim

**Comment by lucasfeliciano** [comment]
As coisas tomaram um caminho onde o readme não será usado como um indice.

Ele conterá informaçoes sobre o projeto: como instalar, como contribuir, como adicionar informação, dependencias do projeto e etc..
