### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by lucasfeliciano** [cainfpucrio/cainfpucrio.github.io#2]
O github tem parceria com o [Jekyll](http://jekyllrb.com/). "Transform your plain text into static websites and blogs."

É bem legal, você escreve em markdown e ele gera o html, fiz meu site com ele www.lucasfeliciano.com.
Ele alem de ser simples de subir é facil de customizar e teremos mais "paginas" que só o README.
Alem disso, pela parceria com o github ele tem compatibilidade out of the box com o github pages onde acessariamos o conteudo em: http://cainfpucrio.github.io

Links uteis
https://help.github.com/articles/using-jekyll-with-pages/

**Comment by leokaplan** [comment]
Ótima ideia!

**Comment by klzns** [comment]
:+1:

**Comment by klzns** [comment]
Se ajudar, fiz um repo que apresenta praticamente todos os recursos do Jekyll + um Grunt pra facilitar a publicação na branch de gh-pages.

https://github.com/brenoc/jekyll-bootstrap

**Comment by lucasfeliciano** [comment]
@brenoc o publish nao seria o push das alterações?
A gente vai trabalhar com PR ( eu acho),se for mesmo acho que nao iremos precisar da task do grunt

**Comment by klzns** [comment]
A ideia é que o source do repositório não fique na mesma branch do código compilado. Por exemplo, desenvolver e dar pull-requests em master e para publicar de fato rodar o grunt para compilar os arquivos e commitar na branch gh-pages.

**Comment by lucasfeliciano** [comment]
Entendi, concordo 100%
:+1:

**Comment by gberger** [comment]
+1

**Comment by lucasfeliciano** [comment]
Done
